baseURL = "http://deepmehta.co.in"
title = "Deep Mehta"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Deep Mehta"
description = "Deep Mehta's Profile"
keywords = "blog,developer,personal,coder,computer,azure,cloud"
info = "Cloud Architect | DevOps Engineer | Software Developer"
avatarURL = "images/profile.jpg"
#gravatar = "images/profile.jpg"
footerContent = "<cite>Life begins at the end of your comfort zone</cite><br><br><b>Read of the month:</b> <cite>Deep Work: Rules for Focused Success in a Distracted World (Cal Newport)</cite>"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = true
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[params.googleTagManager]
id = "6zz4m7owod"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "E-Mail"
icon = "fa fa-envelope"
weight = 1
url = "mailto:mail@deepmehta.co.in"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/deep-mm"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/deepmehta97/"

[[params.social]]
name = "Stack Overflow"
icon = "fa fa-stack-overflow"
weight = 4
url = "https://stackoverflow.com/story/deepmehta"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 5
url = "https://twitter.com/deepmehta97"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Books"
weight = 4
url = "books/"

[[languages.en.menu.main]]
name = "Resume"
weight = 5
url = "resume.pdf"
